name: Software Checks

on:
  push:
    branches: [ smf21, smf20, master ]
  pull_request:
    branches: [ smf21, smf20, master ]

  workflow_dispatch:
jobs:          
  checks:
    runs-on: ubuntu-latest
    name: Software Checks
    steps:
      - uses: actions/checkout@master
        with:
          submodules: true
      - name: Update Build Tools
        run: git submodule foreach git pull origin master
      - name: Checking Sign off
        id: check-signoff
        run: php ./buildTools/check-signed-off.php github
      - name: Checking Licensing
        id: check-licensing
        run: php ./buildTools/check-license-master.php ./
      - name: Checking End of File
        id: check-eof
        run: php ./buildTools/check-eof-master.php ./