name: PHP Syntax Check

on:
  push:
    branches: [ smf21, smf20, master ]
  pull_request:
    branches: [ smf21, smf20, master ]

  workflow_dispatch:
jobs:
  syntax-checker:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ ubuntu-latest ]
        php: [ '5.4', '5.5', '5.6', '7.1', '7.2', '7.3', '7.4', '8.0' ]
    name: PHP ${{ matrix.php }} Syntax Check
    steps:
      - uses: actions/checkout@master
      - name: SetupPHP
        uses: nanasess/setup-php@master
        with:
          php-version: ${{ matrix.php }}
      - run: |
          for file in $(find . -type f -name "*.php" ! -path "./vendor/*"); do
            RESULTS=$(php -l ${file} || true)
            if [ "${RESULTS}" != "No syntax errors detected in ${file}" ]; then
              echo "${RESULTS}A" >&2
              echo "${RESULTS}B" 1>&2
              echo "${RESULTS}C" >>/dev/stderr
              echo "${RESULTS}D" >>/dev/fd/2
              echo "${RESULTS}E" >>/proc/self/fd/2
              ERROR=1
            fi
          done
          exit "${ERROR}"
       - name: SyntaxFailure
        if: ${{ failure() }}
        run: |
          echo ${{ steps.SetupPHP.outputs.stderr }}